name: ✨ Feature Request
description: Suggest a new feature or enhancement for Open Voice Chat
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues and this feature has not been requested before
          required: true
        - label: I have checked the roadmap to see if this feature is already planned
          required: true
        - label: This feature request is related to Open Voice Chat's core functionality
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you want...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which category does this feature belong to?
      options:
        - Voice/Audio Quality
        - AI/Conversation
        - User Interface
        - Performance
        - Accessibility
        - Integration
        - Security/Privacy
        - Mobile Experience
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current workflow)
        - High (Would significantly improve experience)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: checkboxes
    id: user-types
    attributes:
      label: Target Users
      description: Who would benefit from this feature?
      options:
        - label: End users (people having voice conversations)
        - label: Developers (integrating or extending the app)
        - label: System administrators (deploying/managing)
        - label: Content creators (using for streams/content)
        - label: Accessibility users (users with disabilities)
        - label: Mobile users
        - label: Enterprise users

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Example scenarios:
        1. As a [user type], I want to [action] so that [benefit]
        2. When [situation], I need [capability] to [achieve goal]
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots, or links to similar implementations
      placeholder: Drag and drop files here or paste URLs to examples...

  - type: dropdown
    id: implementation-complexity
    attributes:
      label: Implementation Complexity (Your Estimation)
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (few lines of code changes)
        - Moderate (requires some new components or logic)
        - Complex (requires significant architecture changes)
        - Major (requires new dependencies or external services)
        - Unknown

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or implementation ideas
      placeholder: |
        Consider:
        - Browser compatibility requirements
        - Performance implications
        - Dependencies needed
        - Integration points
        - Security considerations

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute to implementing this feature
        - label: I would be willing to help with testing this feature
        - label: I would be willing to help with documentation for this feature

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, research, or links about the feature request
      placeholder: Any additional information that might be relevant...

  - type: input
    id: contact
    attributes:
      label: Contact Information (Optional)
      description: If you'd like us to discuss this feature with you
      placeholder: your.email@example.com
